### ISSUE TITLE
Please merge ctrlcctrlv/aegisite gh-pages as aerch1t3cht/Aegisub branch gh-pages

### ISSUE THREAD

**Issue by ctrlcctrlv** [arch1t3cht/Aegisub#13]
![image](https://user-images.githubusercontent.com/838783/201288665-85663210-4806-4ea5-bdf1-50479d1f7204.png)

https://copypaste.wtf/aegisite

**Comment by ctrlcctrlv** [comment]
I didn't do that much to the website.

I edited download page:

![image](https://user-images.githubusercontent.com/838783/201290518-353530ae-b381-4c80-853f-94018e8eda01.png)

I also made a new blog post:

![image](https://user-images.githubusercontent.com/838783/201290581-ef41db74-75c9-4a10-a5c5-752b6aa6ef33.png)

**Comment by ctrlcctrlv** [comment]
spelled your username right lol
![image](https://user-images.githubusercontent.com/838783/201298958-95aaeef8-aef9-457b-8d1d-840789ed3b7d.png)

**Comment by Ristellise** [comment]
The tag on feels really childish. perhaps consider not doing that.

**Comment by ctrlcctrlv** [comment]
as a furry being childish comes naturally to me

**Comment by arch1t3cht** [comment]
There is now an up-to-date version of Aegisub/aegisite being hosted on https://aegisite.vercel.app/ , and hopefully aegisub.org itself will also be pointed there soon. I was waiting for that to finish, which is why I haven't replied here yet - it took longer than expected but it's done now.

So I won't make a separate website for arch1t3cht/Aegisub itself to make sure there's one definitive website to point to.

I'll also get to your appimage PR when I can, but I need to finish up other features and fixes first.

**Comment by ctrlcctrlv** [comment]
no problem. thanks for maintaining aegisub. i don't care that much about like 30mins of work i put into website :-) and take your time, whenever you get to it in re appimage. it's not so easy to itnegrate into meson.

**Comment by arch1t3cht** [comment]
The domain is set up now: http://aegisub.org/

**Comment by ctrlcctrlv** [comment]
@arch1t3cht Your work is very appreciated. Do you want a recurring donation from <https://foundation.mfek.org>?

**Comment by arch1t3cht** [comment]
I'm sorry for the late reply, I was sick.
@ctrlcctrlv thank you very much for this kind offer. I will say that I'm not really in any grave need of money financially. That said, a donation like that could allow me to buy some hardware for testing on different platforms, and it's possible that in a few months it could give me a bit more time to work on this fork.
So, if you'd willing to support development with this in mind, I'd certainly be honored.
