### ISSUE TITLE
[Bug] Automation scripts are loaded twice at startup

### ISSUE THREAD

**Issue by Akatmks** [arch1t3cht/Aegisub#15]
## Steps to reproduce

1. Prepare an Aegisub DC installation next to arch1t3cht/Aegisub installation.  
2. Add a reasonable amount of automation scripts into the automation folder of both Aegisub.  
3. Use a stopwatch to time the startup for both Aegisub.  

### What should happen?

It should take roughly the same time to start either version of Aegisub.  

### What has happened?

arch1t3cht/Aegisub takes twice as much time to start as Aegisub DC.

### Software version

Tested on Aegisub 2317062 and 3aeca6d Windows portable installation.
Windows 11 Home 21H2.

## My guesses

I noticed that every automation script is listed twice in arch1t3cht/Aegisub's automation menu (I don't mean scripts written in MoonScript; Those are listed four times). I assume this is the cause to the slow startup.  

Thank you!

**Comment by arch1t3cht** [comment]
This is probably the same as https://github.com/TypesettingTools/Aegisub/issues/168 . In particular, it only comes up in the portable build by default, and can be circumvented by changing the autoload path under Preferences > Automation. We discussed possible solutions back then, the simplest one just being deduplication of the autoload paths. But I didn't implement this yet, mostly because this seemed like more of a workaround than a fix. But I'll see if I can implement this now or find a better solution.

**Comment by arch1t3cht** [comment]
It turns out that the above commit didn't properly fix this, so reopening for now. Will fix soon.
