### ISSUE TITLE
XAudio2_9.dll missing -  won't launch

### ISSUE THREAD

**Issue by andiandi13** [arch1t3cht/Aegisub#16]
I tried to update your aegisub, but every version since you added XAudio have this issue at start.

Is something missing on my system ? FYI I have Visual C++ and DirectX June 2010 already installed.

**Comment by arch1t3cht** [comment]
First of all, I assume you mean XAudio2_9.dll ? not XAudio9_2.dll ?

Then, what is your Windows version? Could you list all the Xaudio2_*.dll files you have in C:/Windows/System32 ?

This happens because the CI builds are on Windows 10, so they link against XAudio2_9.dll, which is the latest version there. You probably have an older version of Windows that doesn't have version 2.9. I'll see if it's possible to make it link an older version or package a redistributable with newer builds. Until then you could
- compile Aegisub yourself on your own machine, or
- let the CI do that for you: Fork the repository, change the Windows version from `windows_latest` to your version in `.github/workflows/ci.yml`, and push to let the CI build a different version, or
- [this is a hack, use at your own risk] see if replacing this with a redistributable version works. You could grab an `XAudio2_9Redist.dll` from [here](https://nuget.info/packages/Microsoft.XAudio2.Redist/1.2.10) (navigate to build/native/release/bin/ and double-click the dll there to download it), rename it to just `XAudio2_9.dll`, and throw it into the Aegisub install folder. From what I could test on my win10 machine, this *should* work, but I can't say for sure that it won't break in subtle ways.

    In any case, this last option should allow you to at least *start* Aegisub. You can then set the audio player to something other than XAudio2 (probably DirectSound) in Preferences > Advanced > Audio, after which Xaudio2 shouldn't be called anyway.

**Comment by andiandi13** [comment]
Yes my bad I edited the title.

Alright, it'd be nice to fix that, because I'm on Windows 7 x64 and I guess many are and will have this error.

I tried the 3rd suggestion renaming the redistribuable version of XAudio2_9 and now it launches and everything seems to work. Audio driver is Directsound_old by default.

Thank you. Maybe you should add this to the Readme.
