### ISSUE TITLE
Screenshot Size

### ISSUE THREAD

**Issue by Desbrina** [arch1t3cht/Aegisub#170]
I'm trying to save screenshots from videos using Aegisub, but the resulting images are being squished.

The video plays fine in both VNS and Aegisub with the, but the resulting images is narrower. The screenshot from VLC is fine.

From what I can tell, its because the file has a different storage size to display size.
Storage Size: 720x576
Display Size: 1024x576
Aspect Ratio: 16:9

The dimensions of the save image from Aegisub match the storage size, and VLC matches the display size

Can I get Aegisub to use the display size instead.

**Comment by arch1t3cht** [comment]
This is not possible in Aegisub. Since this would require scaling the picture, I'd say this is out of scope too.

More generally, Aegisub's screenshot tool shouldn't be used for any serious operations. If you need to extract screenshots for some reason, you should probably use ffmpeg or a real media player instead.
