### ISSUE TITLE
Another version ffms2 seeking better

### ISSUE THREAD

**Issue by kedaitinh12** [arch1t3cht/Aegisub#20]
Another version ffms2 seeking better than original ffms2. Unofficial version is here:
http://avisynth.nl/index.php/FFmpegSource#Alternate_Downloads

**Comment by arch1t3cht** [comment]
In what way is this better than upstream ffms2? The changelog given is very brief and the supplied patch has some changes that look questionable, like removing PAFF adjustments entirely.

**Comment by kedaitinh12** [comment]
From test here
https://forum.doom9.org/showthread.php?p=1921568#post1921568
Doom9 forum always use this more than upstream ver

**Comment by kedaitinh12** [comment]
You can check some type of video from here
https://www.dropbox.com/sh/bxwibb20m8rnnro/AABmPSXEWGgE7nBK-PvwyU6Aa?dl=0

**Comment by arch1t3cht** [comment]
I looked into this in more detail now and the vast majority of seeking-related changes seem to just be reverts of upstream changes, including reverts of important fixes. It looks like the improvement in seeking accuracy mainly comes from reverting the PAFF compensation which originally introduced seeking errors, but these have been fixed upstream now and are included in this fork's Windows builds.

Are there any comparisons of StvG builds to the actual *latest* upstream builds, as opposed to 2.40?

**Comment by kedaitinh12** [comment]
Sr, no. Btw StvG just updated recently 
https://forum.doom9.org/showthread.php?p=1982994#post1982994

**Comment by seproDev** [comment]
Not sure if this was ever discussed, but adding dav1d might actually be worth it to enable AV1 playback. Currently, AV1 videos just crash Aegisub on Windows.

**Comment by arch1t3cht** [comment]
@kedaitinh12 Yes, I saw that, and I checked the patches in there before writing my response here.

@seproDev 
> Currently, AV1 videos just crash Aegisub on Windows

It seems that the crash is caused by Avisynth's DirectShowSource, which is tried automatically by Aegisub after other sources like FFMS fail.
I've seen lots of errors or crashes of this kind recently - now that there's more video providers I should probably add some way to enable or disable each of them in the preferences.

> adding dav1d might actually be worth it to enable AV1 playback.

Since dav1d is built with meson, I can see if I can make ffmpeg build with it using the same hack I used for zlib. Until then, AV1 videos still work without issues using Vapoursynth sources like LWLibavSource.

**Comment by kedaitinh12** [comment]
My share ffms2 can open AV1 normally  with wangqr's aegisub

**Comment by arch1t3cht** [comment]
Yes, that's because its ffmpeg was built with dav1d.

I did look into doing the same for the meson build now. I got it to compile, so bestsource works with AV1 now, but FFMS had further problems. The StvG patch fixes those by merging the in-progress pull request https://github.com/FFMS/ffms2/pull/323 and adding a delay computation for AV1 depending on the number of threads being limited. (That latter change seems to be the *only* sane seeking-related change that's not a revert or copied from somewhere.) I'm looking into doing something similar, but I don't want to ship anything before I'm sure it works correctly.

**Comment by kedaitinh12** [comment]
I remember ffms2 will error when decoding AV1 (some frame will corrupt) so StvG set thread limit to fix that

**Comment by arch1t3cht** [comment]
I added dav1d and switched ffms2 to a version with some more hacks to improve VP9/AV1 in e994934e244f8d31dd3238293e6d7f4fed23f5a1 .

**Comment by kedaitinh12** [comment]
Thanks

**Comment by kedaitinh12** [comment]
This unofficial now has source code:
https://codeberg.org/StvG/ffms2/src/branch/doom9
Seeking test with unofficial and official (click to open image), video files to test here:
https://forum.doom9.org/showthread.php?p=1992736#post1992736
