### ISSUE TITLE
No dictionaries post install?

### ISSUE THREAD

**Issue by MeruOtonashi** [arch1t3cht/Aegisub#21]
Hi,

I'm noticing a weird glitch with your 9487 build, though the installer offers to install the english corrector dictionary, once the software is installed, the default English dictionary is not present, thus generating a "No dictionary is available" error.

I had to manually copy over the dictionaries folder into the install folder from another fork of Aegisub in order to get it working again.

**Comment by Toa-of-Gallifrey** [comment]
I'm having a similar issue, except I can't get it to recognize that I've copied the dictionaries folder over. I tried setting a few different paths, but none of them work.

**Comment by arch1t3cht** [comment]
Dictionaries are missing because they weren't yet incorporated into the meson port in TypesettingTools/Aegisub (e.g. they're marked as todo [here](https://github.com/TypesettingTools/Aegisub/blob/8336c7d97cdec30103f301c446d7b970480abbf3/tools/win-installer-setup.ps1#L77)). So while the option to install them exists, it doesn't actually do anything and dictionaries don't get packaged on a clean build where they weren't manually added to the installer-deps directory.

I'm planning to look into fixing this and this issue can track that.

Manually adding the dictionaries (e.g. just copying them from another Aegisub install without changing any settings) should work, though. @Toa-of-Gallifrey if you're sure it doesn't work, can you give more details? E.g. about your file structure and configured paths.

**Comment by MeruOtonashi** [comment]
I confirm that it works.
For me to get the English dictionary going, I copied the dictionaries from the OG release of Aegisub into this build's location:
C:\Program Files\Aegisub\dictionaries

Both aff and dic files must be present for it to be recognized by the app.

**Comment by Toa-of-Gallifrey** [comment]
> Both aff and dic files must be present for it to be recognized by the app.

Thank you, this solved the problem. I had the wrong dictionaries folder; the one from roaming that had only a single dic file. Copying the one from the install that had all the necessary files did the trick.

**Comment by arch1t3cht** [comment]
Fixed in the above commit. In the future I might move to a newer dictionary (e.g. from SCOWL), but for now this just matches what the old official releases shipped.
