### ISSUE TITLE
Importing styles manager styles and Selecting Aegisub as default for .ass

### ISSUE THREAD

**Issue by Samo99** [arch1t3cht/Aegisub#24]
Hi

i tried coping the config from older version to yours but the styles did't appear in the styles manager.
Is there any specific file for it?

**Comment by seproDev** [comment]
They should be saved in the `catalog` folder

**Comment by Samo99** [comment]
> They should be saved in the `catalog` folder

Thank man,

I found it weird cause i used the same aegisub folder that's located in roaming but didn't appeare in arch1t3cht version.
appearntely aegisub only look in the folders in same root as it's .exe and not like the old ones which is aegisub in roaming.

Thanks again man.

**Comment by seproDev** [comment]
It depends on the version you use. If am not mistaken, the portable version from arch1t3cht only looks in the current folder, while the portable AegisubDC version writes in to the `appdata/roaming` folder. I think the arch1t3cht setup version should also use the appdata folder.

**Comment by Samo99** [comment]
On more thing, it seem window don't recognize this as an app for .ass.
Every time i choose arch1t3cht's nothing happen and the icon is not appearing in the menu to apply it. 
Is this behavior because it's a portable even though AegisubDC portable didn't behave like that.
![التقاط](https://user-images.githubusercontent.com/12115578/215684936-8b9cd236-51e6-4708-bdde-36847444e051.PNG)

**Comment by seproDev** [comment]
If you use the setup, it should automatically associate Aegisub with `.ass` files. Otherwise, you should be able to browse for other programs and manually select `aegisub.exe`.

**Comment by Samo99** [comment]
> If you use the setup, it should automatically associate Aegisub with `.ass` files. Otherwise, you should be able to browse for other programs and manually select `aegisub.exe`.

I did brows for the aegisub but nothing happened. i think i'll use the setup instead of the portable.

**Comment by elchinito70** [comment]
I am having issues with Aegisub saving the styles on both, iMac and windows... I create my own styles so that I would use later without going through the same process of editing the subs for every video.. the styles are on the storage but not on the current script, meaning they are not showing when I drag and drop the .srt file to the place where they are edited... it has been a nightmare 
Default
JON
JON - Copy
AYDEN

those are my styles, they are there until I drag and drop the .srt file... but when I do so, the styles are not showing at all... anyone can guide me how to fix this? thanks

**Comment by moi15moi** [comment]
It happen because srt file doesnt support.ass style

**Comment by elchinito70** [comment]
Thanks for the info. I’ll keep that in mind when working with SRT files in the future. But I have always used .srt with aegisub in the past and it’s also happening with .ass files Sent from my iPhone 16Pro Max 256gb On Jul 17, 2025, at 6:06 AM, moi15moi ***@***.***> wrote:﻿moi15moi left a comment (arch1t3cht/Aegisub#24)
It happen because srt file doesnt support.ass style

**Comment by elchinito70** [comment]
In other words. Even using .srt or.ass extensions, the styles disappear as soon as I add one to the blank space where all of us put the subtitles regarding their extension (.srt or .ass) and it is happening in Mac and Windows
