### ISSUE TITLE
[Missing feature] Assdraw

### ISSUE THREAD

**Issue by Samo99** [arch1t3cht/Aegisub#25]
I'v noticed that assdraw is missing.
Can you please add it in the next update?

**Comment by seproDev** [comment]
It was removed from the TStools fork due to near to no usage, and better alternatives existing (see https://github.com/TypesettingTools/Aegisub/issues/54).
I think arch1t3cht shares a similar sentiment regarding assdraw, so it is unlikely to be added back in.

Most people use either clip to shape scripts ([Everything Shape](https://typesettingtools.github.io/depctrl-browser/macros/zf.everythingShape/), [Masquerade](https://typesettingtools.github.io/depctrl-browser/macros/ua.Masquerade/)) or Adobe Ilustrator ([AI2ASS](https://typesettingtools.github.io/2014/08/25/typesetting-with-illustrator-and-ai2ass-part-1.html)).

**Comment by Samo99** [comment]
Oh, i see now.
Thanks for the clarification.
