### ISSUE TITLE
mutliple errors with automation scripts

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#30]
https://pasteboard.co/BIjBzmQgGwzc.png
also...a scrollable automation window would be very helpful

**Comment by arch1t3cht** [comment]
The error you linked does not come from any script shipped with Aegisub, so it should be reported to the relevant repository.
(In this case, it's a known issue with ASSFoundation that's been fixed [here](https://github.com/TypesettingTools/ASSFoundation/pull/9), but there hasn't been a version bump since then.)
