### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#34]
how about a built in tool to do curved text easily

**Comment by arch1t3cht** [comment]
It's the same answer as for the tool for gradients. There are already lots of automation scripts that do this, and for more advanced usage this can be done with tools like Adobe Illustrator and exported to .ass . Right now it wouldn't be worth the effort to add a visual tool for this when this would almost surely miss some of the features in automation scripts and be harder to improve or extend. This is also because effects like gradients or curved text would require splitting a line into multiple ones, which none of the current visual tools can currently do. So this is different from the perspective tool which always only affects the global tags of one single event.
