### ISSUE TITLE
averaging of color picker

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#36]
heres another feature aegisub said they were gonna add one day..but its been a LONG time since I heard anything more on it

https://github.com/Ristellise/AegisubDC/issues/41

**Comment by arch1t3cht** [comment]
Same as #35 . There is no reason to make an issue for this - I watch all of the other relevant Aegisub repositiories and I'm aware of most of the big "feature requests".

Also, who said "they were going to add" it? All I see is an open issue.

I will say that I did think about this feature since day one of this fork but put it on hold because there's some subtleties to work out - how to integrate this with the two-step picking process into the current color dialog? What would be a sensible choice of averaging windows? Is it enough to average in RGB or should there be some colorspace conversion first? ...etc.

Average color picking can easily be done in image editors like GIMP without too much extra effort. Or you can use the Vapoursynth video provider to blur the video and then sample that in Aegisub.

All of those are reasons for why this is not a high priority feature.
