### ISSUE TITLE
xbord,ybord feature

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#40]
new gui tool for modifying these values

**Comment by arch1t3cht** [comment]
While this would at least be *possible* to implement, it still fails two of the points I explained in #35 - on its own, it wouldn't fit nicely into Aegisub (since there could just as well be tools for normal \bord, \shad, \xshad, \yshad, and also other numerical values), but even more importantly it's not really necessary. Any graphical tool would just amount to typing in numbers anyway.

I have asked you before to stop making these kinds of stream-of-consciousness issues that don't seem to have any more thought behind them than the one-sentence messages you write in them. Next time I'll block you from this repository.
