### ISSUE TITLE
Negative Letter Spacing

### ISSUE THREAD

**Issue by Mynona666** [arch1t3cht/Aegisub#48]
![FSP](https://user-images.githubusercontent.com/68801931/231413777-acb8d3a4-ebff-4fa9-b62a-10a8c1741787.jpg)
Hello, I saw that in this version we could in the style directly put negative spacing between the letters but a priori it does not take it into account. Obliged therefore to always put it in the text field of the frame. Is this normal or a bug?

**Comment by arch1t3cht** [comment]
It turns out that, while Aegisub correctly sets the spacing, negative spacing in styles [isn't actually supported by the renderers](https://github.com/libass/libass/blob/9b3c0d5b350e13eb69dc87b52751ec0ad44280af/libass/ass.c#L713), so this is not possible after all.
I'll revert this change soon to reduce the chance for confusion. Thanks for pointing this out.
