### ISSUE TITLE
feature: multi copy and paste

### ISSUE THREAD

**Issue by eddilara** [arch1t3cht/Aegisub#53]
a feature where you could copy and paste multiple  things..in like some kinda right click menu
I often need to copy multiple things...and instead of having only 1 thing on the clipboard at a time it would be very helpful to have many things able to be copied/pasted

**Comment by arch1t3cht** [comment]
Depending on what you mean (you've again been extremely vague) this is likely solved by some combination of
- Copy/pasting multiple lines
- The "Paste lines over" functionality
- The clipboard history that most operating systems support now (and if they didn't, that part would be outside of Aegisub's control)
- Existing automation scripts like MultiCopy or Paste from Pad

If what you want is *not* achieved by something like this, then I can't help you either since there's no way to tell from the issue description what your concrete use case is, or what concrete feature you expect to be added.

With this, this issue is exactly like the previous ones you have made here, which I have explicitly asked you to stop with multiple times. I will be blocking you from this repository now.
