### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Colerar** [arch1t3cht/Aegisub#54]
I am not a lawyer or an ardent supporter of the GNU project. However, I would like to bring to your attention the following concern:

This fork incorporates some dependencies licensed under the GPL, which makes distributing it under the BSD-3 license a potential violation of the GPL license.

For instance, both [`x264`](https://github.com/videolan/x264) and [`x265`](https://github.com/videolan/x265) are distributed under GPLv2.

A possible solution to this issue could involve allowing users to select which encoders to enable through compile options, similar to the approach taken by FFmpeg.

**Comment by arch1t3cht** [comment]
I'm not sure which exact dependencies you mean here (or which way of distribution) - x264 and x265 aren't used as direct dependencies anywhere, and are [not linked into ffmpeg](https://github.com/arch1t3cht/Aegisub/actions/runs/4502380945/jobs/7924119697#step:9:1166) on Windows builds, partly for that exact reason.
One GPL-licensed library that *is* a direct dependency of Aegisub is FFTW, but that is already an optional dependency that can be enabled through compile options and is [not linked in by default](https://github.com/arch1t3cht/Aegisub/actions/runs/4502380945/jobs/7924119697#step:9:1166).

Also, by "This fork incorporates", do you mean that these license issues were introduced by this fork, or that they're issues carried over from upstream (either Aegisub/Aegisub or TypesettingTools/Aegisub)?

**Comment by TheOneric** [comment]
IANAL, etc...

Every typical Aegisub build includes GPL components and this is not specific to arch1t3cht/Aegisub. For TypesettingTools/Aegisub, I commented on this before [here](https://github.com/Aegisub/aegisite/pull/13#issuecomment-1072769419) (see for more details on non-BSD bits).
Notably, even in Aegisub’s very own source, CSRI *(in practice used only in Windows builds nowadays; RIP asa)* code contains GPL licenced files.

However, besides `README`’s claim that *“All files in this repository are licensed under various GPL-compatible BSD-style licenses”* and the self-description as “BSD_style licenses” being inaccurate (for Windows builds) it is not obvious to me why GPL bits being contained in or linked to from the builds should be problematic. Afaict all licences are GPL-compatible so the resulting binary is effectively GPL-licenced (and technically `GPL(v2+|v3) AND ...` where all following conditions are a subset of `GPL`.
`README` also already points this out: *“The official Windows and OS X builds are GPLv2 due to including fftw3.”* (although there’s more than just fftw). And iirc the Windows installer also again refers to the GPLv2.

Problems *could* arise if:
  - a `--enable-nonfree` ffmpeg builds *(e.g. with libfdk_aac)* get bundled with published binaries (not GPL-compatible)
  - some deps or optional-but-bundled libraries are GPLv2-only and others GPLv3-only *(haven't checked)*
    - even if it’s just `GPLv2-or-later` and some `GPLv3-(only|or-later)` the Windows installer and README should be updated to refer to GPLv3 instead of GPLv2.
  - published binaries do not contain a copy of the licences where this is required (e.g. GPL) or do not honour the attribution of all copyright holders *(haven't checked either, I’m building my own binaries for personal use only)*
  
  @Colerar, does any of those problems apply or do you see something else which is problematic?
