### ISSUE TITLE
bas or bs?

### ISSUE THREAD

**Issue by 0tkl** [arch1t3cht/Aegisub#65]
When I'm packaging your release to [aegisub-arch1t3cht](https://aur.archlinux.org/packages/aegisub-arch1t3cht), I'm a bit confused about the dependencies in the code: it depends on VapourSynth BestAudioSource plugin (bas) in somewhere, but BestSource plugin (bs) in other places.

I notice that bas seems to be the predecessor of bs, and bas had been archived in 2022. I tried to migrate from bas to bs (see https://github.com/arch1t3cht/Aegisub/commit/23451d4), and it works fine on my Linux. Could we migrate from bas to bs (after testing on Windows and macOS)?

**Comment by arch1t3cht** [comment]
Yes, `bs` is the successor to `bas` and generally recommended to be used instead. The only reason why I'm not moving to it as the default yet is that it doesn't have any official builds available (only beta builds from doom9).

AFAIK the actual vapoursynth plugin `bs` isn't actually used anywhere (by default), it's only `bas` and the BestSource *library*, since that can easily be built and linked against the ffmpeg wrap.

If the problem with there being no official `bs` plugin builds persists even longer, I might eventually just set up a compile workflow for it myself, but I didn't get around to it yet.

**Comment by hooke007** [comment]
win build https://github.com/vapoursynth/bestsource/actions/runs/5531102539

**Comment by 0tkl** [comment]
https://github.com/vapoursynth/bestsource/releases/tag/R1-RC1

**Comment by arch1t3cht** [comment]
Yeah, I'll wait and see if there'll be a proper (non-RC) release soon. If not, I'll just ship the RC1.
