### ISSUE TITLE
[Bug] Opening multiple instances of Aegisub at the same time generates unexpected bugs

### ISSUE THREAD

**Issue by VegethB** [arch1t3cht/Aegisub#7]
As the title suggests, if several Aegisubs are opened at the same time, "random" bugs are generated, the most frequent one is shown in the video (since sometimes it doesn't just happen that specific bug but others).

Bug1)

https://user-images.githubusercontent.com/17975351/192144347-c440d402-3519-4b56-bca3-9a8a170836bf.mp4

<details>
 <summary>Bugs screen:</summary>

Bug2) ![Immagine 2022-09-25 153427](https://user-images.githubusercontent.com/17975351/192146356-93fe4bd2-15ae-427f-9c99-1af979e57841.png)
![Immagine 2022-09-25 153501](https://user-images.githubusercontent.com/17975351/192146363-d511c701-0bab-4887-a3ec-f78cde9b797c.png)

Bug3) ![image](https://user-images.githubusercontent.com/17975351/192155023-fc877015-05b3-47bf-8c53-b80961de19f2.png)
![image](https://user-images.githubusercontent.com/17975351/192155057-12e84af7-7dce-4172-affd-e432ac849503.png)
![image](https://user-images.githubusercontent.com/17975351/192155078-dc933bd6-4c56-4ed8-ae97-fa631678528e.png)
![image](https://user-images.githubusercontent.com/17975351/192155190-baf3e1db-7c48-4ad9-9087-37bfdc4efe39.png)

</details>

The most obvious thing to think about is that it is due to the program's inability to create unique logs for opened files.
However, this extends to prevent certain scripts from being loaded (generating an automation script not loaded error).

Why open multiple instances like this instead of opening them manually (thus allowing at least 1 second to pass):
I have to mark the times in ms of the RAWs.
As long as you do 12 ep a day it's not a problem... Different speech if I have to open series of 300+ episodes.
Those 3 seconds of doing it by hand change the whole day (also because at a certain you break to repeat the same action 300 times).

Steps:
- Select 2+ video files;
- Using batch script or context menu ("open with" is the same thing I do in the video) open the selected files;
- If they are opened without problems, repeat the above steps until an error appears;

To do what I do in the video (open aegisub from the context menu):
Create keys in the registry like this 
![image](https://user-images.githubusercontent.com/17975351/192144656-45862d7d-61ad-45f9-87ff-0050e146302e.png)
![image](https://user-images.githubusercontent.com/17975351/192144671-38c07ce4-7e18-4173-808f-774e0a2c29ef.png)
`"C:\SoftWarez\arch1t3cht's Aegisub fork\aegisub-Arch1t3chts.exe" "%1"`

HW Specs:
I7-4790k 4ghz;
Kingston sata3 SSD;
Network Paths 1gb / s (sata3 network drive);
20GB DDR3 1600mhz
Nvidia GTX1070ti 8gb

### **NOTE!**
This bug happens with any aegisub mentioned in the readme (code), AegisubDC, AegisubTypesetTools and the official Aegisub.
In the case of this video, the Aegi of this Github was used in portable mode (because AegisubDC is still the main one).
In the particular case of this build, I tried with Avisynth + (the latest to the day of this post), as source video (instead of the usual ffmpeg), nothing has changed.
In AegisubDC, vsfiltermod (instead of libass) is used to view subs

[logs.zip](https://github.com/arch1t3cht/Aegisub/files/9640809/logs.zip)
[crashlog.txt](https://github.com/arch1t3cht/Aegisub/files/9640810/crashlog.txt)

Thanks in advance.

_Long and complete video of: What is all this mess for 🙃_ https://mega.nz/file/x4EViaTL#5WwRS_XH3tjThV4cJ-onZNEtn4joLFQ05Gw8prmeXOs

**Comment by arch1t3cht** [comment]
...It's not like I ignore issues on purpose. But bugs like these, which are actually collections of multiple issues, some of which are very hard to debug or work around will just take time to fix.

Also, please read the repository's README:
> I'll gladly take any bug reports, but if you encounter an issue, please check first if it occurs only on my fork, or also on [earlier TSTools builds](https://github.com/TypesettingTools/Aegisub/actions). If it wasn't introduced by my fork, I can still take a look, but I can't promise anything.

Bugs that weren't introduced by my own changes will get a lower priority when there's more important things to fix. Especially when it's bugs like this one that come up in niche situations and have simple workarounds (e.g. making a wrapper script that starts multiple instances of Aegisub with some delay in between)

But, since you closed the issue, it's probably not important any more :)

**Comment by seproDev** [comment]
> 1 year and 3 months

You might want to double-check your maths here.
But I am sure arch1t3cht is happy to issue a full refund to you for all the pain and suffering he caused by not spending his time on your very niche use case.

Also, looking at your video, I don't understand why you want to open a new Aegisub instance for each video. Can't you just drag and drop the next episode into Aegisub once you have noted down the timestamp? Alternatively, as it doesn't seem like you need all episodes open simultaneously, you could just write a simple script to open every video in the folder one after another, waiting for the previous Aegisub instance to close.

**Comment by arch1t3cht** [comment]
@juice_squad

**Comment by arch1t3cht** [comment]
They're blocked now, but anyone else reading this can refer to this as the perfect example of what not to do in open source repositories.
