### ISSUE TITLE
Adding a feature to clip tool

### ISSUE THREAD

**Issue by Samo99** [arch1t3cht/Aegisub#86]
Hi

Is't possible to add the ability to rotate "\frz" a clip specially the rectangular clip?

**Comment by arch1t3cht** [comment]
Rotating a rectangular clip is not something that can be done from Aegisub's side since it concerns the renderer.
Rotating a vector clip is certainly something you might want from time to time, but it doesn't really fit too well into Aegisub itself. You'd be better off with Automation scripts (e.g. with Shapery you could run Clip2Shape, then transform your Shape as needed, and then run Shape2Clip to get back a clip).
