### ISSUE TITLE
Japanese input in the main edit box not working on MacOS Sonoma 14.0 (23A344)

### ISSUE THREAD

**Issue by islands13** [arch1t3cht/Aegisub#91]
Japanese input in the main edit box not working after updating to MaxOS Sonoma 14.0 (23A344), probably caused pending input failure.
The problem was supposed to be solved on https://github.com/Aegisub/Aegisub/releases/tag/v3.2.0 according to the chagelog.

**Comment by brdick** [comment]
Reproducable for me, only switching from Japanese to another language helps and adds the input text.

**Comment by pilisir** [comment]
It also reproduces in Mandarin Phonetic Symbols for Taiwanese.
Can not finish typing with Return, but shows up after Tab or Esc.

**Comment by arch1t3cht** [comment]
The fix for this was reverted in c487dd2bdbab58ad9f50da6624132165abd7a123 because it's a hack that uses private symbols in wx and thus may not work with upstream wx. Since the builds on this repository build wx in a subproject on osx, I brought the fix back. If that causes problems I'll have to see what I'll do.
